// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDO5E1FOWFD6qQZwmNIX5OMA-fc0ntJBDE',
    appId: '1:296143700253:web:2b412b8a3716abf79e21f4',
    messagingSenderId: '296143700253',
    projectId: 'real-imobil-7dad9',
    authDomain: 'real-imobil-7dad9.firebaseapp.com',
    storageBucket: 'real-imobil-7dad9.appspot.com',
    measurementId: 'G-H03R6GX3CC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhbqJkkUOxpwnzq9sE_1rv4mKIMtFsdMI',
    appId: '1:296143700253:android:2b0c68fbaf87f5e79e21f4',
    messagingSenderId: '296143700253',
    projectId: 'real-imobil-7dad9',
    storageBucket: 'real-imobil-7dad9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqSzOswaH-X96-NJALnlhu8K865rNRPhg',
    appId: '1:296143700253:ios:35698e84958674be9e21f4',
    messagingSenderId: '296143700253',
    projectId: 'real-imobil-7dad9',
    storageBucket: 'real-imobil-7dad9.appspot.com',
    iosBundleId: 'com.example.real-imobil',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDO5E1FOWFD6qQZwmNIX5OMA-fc0ntJBDE',
    appId: '1:296143700253:web:37f3c72ef936b4fc9e21f4',
    messagingSenderId: '296143700253',
    projectId: 'real-imobil-7dad9',
    authDomain: 'real-imobil-7dad9.firebaseapp.com',
    storageBucket: 'real-imobil-7dad9.appspot.com',
    measurementId: 'G-JF8J7C4G80',
  );
}
